# Generated by Django 4.0.4 on 2022-05-18 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
