# Generated by Django 4.0.4 on 2022-05-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0005_product_user_alter_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
