# Generated by Django 4.0.4 on 2022-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0006_alter_product_payment_status_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(null=True),
        ),
    ]
