# Generated by Django 4.0.4 on 2022-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0009_alter_participantshistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interval_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='endsession',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
