# Generated by Django 4.0.4 on 2022-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0012_auctionuser_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionuser',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
