# Generated by Django 4.0.4 on 2022-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0013_auctionuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
